### ISSUE TITLE
Please add .gitignore file.

### ISSUE THREAD

**Issue by hsluoyz** [yuin/gopher-lua#144]
As the title.

**Comment by bontibon** [comment]
What should be ignored?

**Comment by hsluoyz** [comment]
e.g. IntelliJ IDEA files, because I use IDEA to open lua project.

**Comment by apparentlymart** [comment]
@hsluoyz rather than adding a `.gitignore` to each repo you work on, you may find it simpler to create a [global gitignore file](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore) on your computer where you can ignore the temporary files created by the tools you usually use, which will apply regardless of what appears in each repository.

**Comment by hsluoyz** [comment]
fair enough, thank you!
