### ISSUE TITLE
VM main loop: Opcode switch instead of opcode array -> func results in ~15% speed increase in fib

### ISSUE THREAD

**Issue by jakevn** [yuin/gopher-lua#195]
I was curious what the overhead is for the use of function calls in op code dispatch in the VM main loop, so I experimented by changing the loop into a switch statement with each opcode handler inlined in the case. In the fib(35) benchmark, I noticed an approximately 15% increase in performance. 

The immediately identifiable downside here is that there are both `mainLoop` and `mainLoopWithContext`. I didn't want to continue any further in seeing whether or not it would be worth pursuing a solution which would allow this optimization, as well as further benchmarks, until I gauged the interest of the contributors.

I would be happy to provide a fork or PR with my changes if there is interest.

**Comment by yuin** [comment]
@jakevn In earlier versions of GopherLua uses a switch statement instead of function calls(jump table). (see https://github.com/yuin/gopher-lua/blob/7a43a95fe5a028fb1b501bbe880dea7dab9ccf7d/vm.go )

At that point, the jump table was faster than the switch statement.

Generally, opecode dispatch methods(threading methods in high-level programming languages) are:

- Direct threading(generally fastest): Can not implement in Go(labels can not be variables)
- Switch threading : earlier version of GopherLua
    - Performance depends on
        - compiler optimization
            - AFAIK, Go compiler does not optimiaze switch statements more than the binary search.
        - cpu architecture
            - branch detection
- Table jumps + fuction calls : current version of GopherLua

If the switch threading got faster than the table jumps it might mean that Go compiler had changed switch statment optimizations. Or it may be characteristics of CPU used for benchmarking.

Do you have any information about Go compiler changes? What cpu did you use for benchmarking fib(35)?

**Comment by jakevn** [comment]
@yuin Thanks for taking the time to post such an informative response! Interesting that the previous implementation used switch instead of jump table/func.

The fib(35) benchmarks were performed on a newer i7 laptop processor (x86-64) using Go 1.10. I don't recall ever seeing any relevant optimization in the past few Go releases, so I imagine you are correct that this result is likely not broadly applicable. In fact, another microbenchmark (1 million for loop iteration with numeric addition) was slower in the switch statement by about the same amount it was faster in the fib benchmark.

I am going to close this issue as it is likely there is nothing to be gained here. Thank you for creating such a great project. I hope I can provide useful contributions in the future.
