### ISSUE TITLE
glua with require

### ISSUE THREAD

**Issue by ghost** [yuin/gopher-lua#263]
Is it possible?

~~~
$ cat sun.lua
local http = require("http")

$ glua sun.lua
sun.lua:1: module http not found:
no field package.preload['http']
CreateFile .\http.lua: The system cannot find the file specified.
CreateFile C:\opt\lua\http.lua: The system cannot find the path specified.
CreateFile C:\opt\lua\http\init.lua: The system cannot find the path specified.
~~~

https://github.com/yuin/gopher-lua#standalone-interpreter

**Comment by cup** [comment]
https://github.com/cjoudrey/gluahttp/issues/24

**Comment by bbuck** [comment]
What "http" are you trying to require? It's very possible, the output tells you where it's looking for the file.

```
CreateFile .\http.lua: The system cannot find the file specified.
CreateFile C:\opt\lua\http.lua: The system cannot find the path specified.
CreateFile C:\opt\lua\http\init.lua: The system cannot find the path specified.
```

If any of those files exist, `require("http")` will load that file.

This looks like the default paths gopher-lua uses, if you want to point it to a different path then you can set `LUA_PATH` Env variable.

If I do the same thing you did:

```
~/Dev/lua
❯ cat sun.lua
local http = require("http")

~/Dev/lua
❯ glua sun.lua
sun.lua:1: module http not found:
	no field package.preload['http']
	stat ./http.lua: no such file or directory
	stat /usr/local/share/lua/5.1/http.lua: no such file or directory
	stat /usr/local/share/lua/5.1/http/init.lua: no such file or directory,
```

You can see our paths are similar, if I did `LUA_PATH=~/Dev/lua/?.lua glua sun.lua` 

```
sun.lua:1: module http not found:
	no field package.preload['http']
	stat /Users/username/Dev/lua/http.lua: no such file or directory,
```

You can see there is only one stat line instead of 3, and now it's looking in `/Users/username/Dev/lua` instead of `/usr/local/share/lua/5.1/`. So you need to point gopher-lua to your libraries if you want to require them.
