### ISSUE TITLE
Benchmark against other Lua implementations

### ISSUE THREAD

**Issue by leolara** [yuin/gopher-lua#52]
It would be good if the benchmark would compare with http://luadist.org/ that seems a more reasonable baseline to see how much improvemnt can be done in terms of performance.

**Comment by yuin** [comment]
Currently Go is not suitable for writing **fast** interpreter, I think.

Interpreter optimization techniques that can be used in C can not be used in Go.

- Direct threading: Go does not have goto-label as value. And Go compiler uses Plan9 assembler, it is hard to implement switch optimizations that better than binary searching.
- Efficient variants:
    - Tagged value: It will break Go memory management
    - Union: Go does not have any union types
    - (Go's interface is slow)
- Macro: Go does not have any macros, and Go function call is slower than C due to register specifications.
- Inlining: Go's compiler executes inlining only for some very limited situations.
- JIT: There is an experimental implementation JIT for Go ([nelhage/gojit](https://github.com/nelhage/gojit)), but it is hard to support all platforms(But I think  JIT is only possibility to gain more performance).

Interpreters that are implemented by JAVA or C# are fast because JAVA and C# have a JIT engine. Go generates single binary executable and it has no JIT.

For the above reasons, it is hard to compete in performance with interpreters that are implemented by C. So I want to start interpreters that are implemented by Go. (Of course, there is [a benchmark page](https://github.com/yuin/gopher-lua/wiki/Benchmarks) on the wiki, your contribution is wellcome!)

**Comment by leolara** [comment]
@yuin still I think it would be interested to see how far is this implementation to C based performance.

**Comment by Splizard** [comment]
Is there anything which can be done in Go (in order to speed up the interpreter)?

**Comment by yuin** [comment]
Unfortunately, there is not much we can do about that.
GopherLua is, so far as I know, a fastest script language implementation in pure Go.
Even if script languages that are implemented in C and have binding in Go(see https://github.com/olebedev/go-duktape) are included, GopherLua is one of the fastest implementation.

Yet, pseudo unions and stack based APIs may possibly increase performance by reducing memory allocations, I think. Go interface is painfully slow due to causing implicit memory allocations, so it is important for performance to reduce use of interfaces.

**Comment by yuin** [comment]
I've just added Python3.4 and Lua5.1.4 to the [Benchmark page on Wiki](https://github.com/yuin/gopher-lua/wiki/Benchmarks) . Go1.7 GC seems to do a good job, now GopherLua is faster than Python3.4 on the fib35 benchmark.
