### ISSUE TITLE
how do you think of supporting closure serialization of lua?

### ISSUE THREAD

**Issue by xtaci** [yuin/gopher-lua#57]
Closure serialization, which means code and it's context partly evaluated.
In my business, If a closure can be serialized, it can be passed to remote service to apply with the input provided by the remote service.

a closure(args1...N) -----> remote service(   apply(closure,input)  )

This feature is quite useful in distributed system, for example:
1. Data broker
2. Remote data warehouse analyze

Without this, I can only implement Context(some arguments provided) + Code Snippet String (not evaluated) to remote service and Apply(Context, Args, Code)

How do you think of this?

PS:
https://github.com/jeremeamia/super_closure

**Comment by yuin** [comment]
Closure serialization in GopherLua is quite hard to make it possible for some reasones.

1. GopherLua is based on Lua5.1 : Closures in Lua5.1 refers the global environment. (Lua5.2 or newer has no global environment. The global environment  is expressed as an upvalue.).
2. GopherLua does not have bytecode dump functionality : Byte codes in Gopher are just intermediate representation.

If it is must, I'd probably try that like this:

1. Assumptions1 : Ａ local and remote VM share the same global variables.
2. Assumptions2 : Closures do not have a metatable.
3. Assumptions3 : Closures do not refer any upvalues.
4. Dump an LFunction object into a byte array by `encoding/gob` ( `LFunctionProto` has private members, so you will have to reflections) .
5.  Load the byte array and set `clo.Env = (remote global LTable)` .

**Comment by xtaci** [comment]
Yes, It's hard, but it's quite useful.

Instead of distributing data, we can distribute procedures, It is much more useful than data only parallel.
All Assumptions are acceptable at this stage I think. 
I really hope this feature can be added to gopher-lua.  

(Assumption3. Upvalue capturing  is hard, I think AST will help.)

**Comment by yuin** [comment]
If it is possible to implement as a library, that should not be included GopherLua because GopherLua is Lua. Lua's philosophy is to keep itself as small as possible, but to provide functionalities that make it possible to add major language features as needed.

If you need to some functionalities to implement it, I will examine new functionalities that help you.

**Comment by xtaci** [comment]
It's too hard for me alone to implement this.
If you start a new library to do this , I can contribute some code.

**Comment by xtaci** [comment]
If I can get AST from a compiled closure，I can recursively find all the upvalues myself.

**Comment by yuin** [comment]
You had better stop handling upvalues.

In original Lua5.1, functions with upvalues can be dumped by `string.dump`, but all upvalues are initialized with `nil` and not shared with any other functions.
In addition, in original Lua5.0, functions with upvalues can **NOT** be dumped by `string.dump` (causes an error).

These facts underline the the difficulty of handling upvalues in this job.

**Comment by xtaci** [comment]
so you still suggest manually SetGlobal(variables) & DoString(`function f()`) ?

**Comment by yuin** [comment]
Yes, It is simplest way.
Or, write serializer for the `FunctionProto` struct using some reflections(yes, nearly equals to `string.dump`) and construct an `LFunction` object without upvalues(or with nil initialized upvalues).

`encoding/gob` will not be suitable for writing a  serializer for the `FunctionProto` struct because it has some unexported fields.

**Comment by xtaci** [comment]
![broker](https://cloud.githubusercontent.com/assets/2346725/12005394/8c2edc66-abdd-11e5-9705-896eb8653a29.png)

this is a sample for how I use it.  A name change procedure to be executed in remote.

**Comment by shabbyrobe** [comment]
I have a very similar use case to this. I was thinking I could mark certain functions that I care about and extract the code from the AST, but that doesn't look possible either because the AST only contains line numbers, not token positions. Am I missing something? If not, would you accept a PR that puts the token positions into the AST?
