### ISSUE TITLE
os.clock should not use wall time

### ISSUE THREAD

**Issue by dlclark** [yuin/gopher-lua#59]
The current implementation of os.clock uses a simple "seconds since the app started" but the LUA reading material I'm seeing (e.g. http://www.lua.org/pil/22.1.html) says it should be CPU-seconds.

I don't know of a clean way to get this via the Go runtime, so this would require a kernel call to getrusage (http://linux.die.net/man/2/getrusage).  For some reason getrusage returns wall clock time on Windows, so you'll need to use GetProcessTimes (https://msdn.microsoft.com/en-us/library/windows/desktop/ms683223.aspx).

**Comment by yuin** [comment]
Thanks, but there is a little misunderstanding.

One of the most important feature of Lua is a portability.  [Lua readme](http://www.lua.org/manual/5.3/readme.html) says "Building Lua should be straightforward because Lua is implemented in pure ANSI C and compiles unmodified in all known platforms that have an ANSI C compiler" . 
That is, platform dependent functions like `GetProcessTimes` are not used in Lua. In fact, Lua uses `clock()` (in `time.h`) to implement `os.clock()`.

man clock(3):

>> **On several other implementations** , the value returned by clock() also includes the times of any children whose status has been collected via wait(2) (or another wait-type call).

Whether or not the result of `clock()`  includes CPU-seconds of child processes is not defined.
If not considering child processes, `clock()` will be the same as "seconds since the app started" mostly .

Therefore, I would like to make no changes to GopherLua.

**Comment by dlclark** [comment]
That makes a certain sense, but providing os-specific implementations doesn't decrease portability. Instead it increases uniformity across all platforms for the scripts. 

The present code is also uniform across platforms, so my issue was more that I expected my lua script under GopherLua to work the same as luac on the same system.  I'm guessing the script would work the same if it was on a Windows machine, but on a UNIX variant it differs between the two runners. 

I can certainly understand if this issue should be closed as preferring simplicity of implementation and uniformity over replicating luac behavior.

**Comment by yuin** [comment]
In the first place, `clock()` bahaviour is different between Windows and Linux. In other words, `os.clock` works differently on different platforms.

>> I can certainly understand if this issue should be closed as preferring simplicity of implementation and uniformity over replicating luac behavior.

I  give preference to simplicity of implementation over the original lua implementation, so I would like to close the issue.

If you need more original lua implementation compatibility, you can replace `os.clock` with your implementation.
