### ISSUE TITLE
Golang packages

### ISSUE THREAD

**Issue by prsolucoes** [yuin/gopher-lua#70]
Hi,

I want integrate it on my project:
https://github.com/prsolucoes/goci

It is a continuous integration system that use script files to make the build steps. I want use LUA now. How i can export some Go packages to this implementation? How multiple return works in this LUA implementation?

Thanks.

**Comment by yuin** [comment]
Hi,
GopherLua is a Lua5.1 implementation, so  reading [Lua 5.1 reference manual](http://www.lua.org/manual/5.1/) might be helpful and you should be familiar with original Lua5.1(GopherLua has same API as original Lua5.1). 

>> How i can export some Go packages to this implementation?

Please refer to [Creating a module by Go](https://github.com/yuin/gopher-lua/blob/master/README.rst#creating-a-module-by-go) .

>> How multiple return works in this LUA implementation?

Almost same as original Lua5.1 implementation. GopherLua uses objects instead of stack indicies. Please refer to [Calling Lua from Go](https://github.com/yuin/gopher-lua/blob/master/README.rst#calling-lua-from-go) .

**Comment by prsolucoes** [comment]
Ok, nice.

Fist question is about error handling. Other libs that im using to integrate has a problem in calling functions with 3 types of error:

1 - Call a export function to LUA using fewer params number
2 - Call a export function to LUA using too many params number
3 - Call a export function to LUA using invalid type param

This is a common problem when user develop their scripts, but another lib simply CRASH the host process!

How it works on this lib?

Second question: It is in active development? Have any contact (email, skype, hangout)?

Third question: You see any problem to use it in my project? Any limitations?

Thanks. Sorry for questions, but it is an important search to my project.

**Comment by yuin** [comment]
1

Same as original Lua5.1 implementation.  You can either let it crash when there is a problem with parameters or handle the error.

2

>> It is in active development?

Yes it is.

>> Have any contact (email, skype, hangout)?

Sorry this is just a hobby project, I can not give you that.

3

GopherLuas is FLOSS. 

If you can not read the GopherLua sources and can not solve the problem by yourself, it is hard to use this library for your project. I recommend you to use other libraries.
